### PR TITLE
Relicense CoursePlan under MIT

### PR DESCRIPTION
**Pull request by zachary-kent**
### Summary 

Re-licenses CoursePlan under MIT, which is far more permissive that AGPL and has no associated copyleft provisions. Derivative works can use our code however they please as long as they preserve the license and copyright notice.

### CODE REVIEW

**Review by noschiff — COMMENTED** [review]
I believe you may need to get permission from all contributors to this repository in order to change the license of their work.

**Comment by zachary0kent** [comment]
> I believe you may need to get permission from all contributors to this repository in order to change the license of their work.

I'm pretty sure the CLA we signed lets DTI relicense our work. I'll check again though.

**Comment by zachary0kent** [comment]
> I believe you may need to get permission from all contributors to this repository in order to change the license of their work.

Yep, although *I am not a lawyer* this part of the CLA is pretty clear:

> Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to DTI and to recipients of software distributed by DTI a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.

**Review by rohanmaheshwari430 — APPROVED** [review]
Thanks for addressing this. To address Noah's concern, DTI members do not have any ownership over their contributions as outlined by the CLA, so a shift in the licensing should not require any members' consent.

**Pull request merged**
