### PR TITLE
January 2022 Release

### PR DESCRIPTION
**Pull request by benjamin-shen**
### Summary 

Potentially breaking changes:
- bug fixes
  - new year dropdown bug
- updated requirements data
  - new AS, EAS majors
  - updated CS major
  - fixed checkers (no need to test)
- specializations
- analytics data & route
- AP/IB infra update
- two-graph requirements infra (no visible changes expected yet)

Features in progress:
- templates, placeholder courses
- dashboard, improved routing system
- constraint violations & overridden fulfillments

Scripts:
- semester type renamed to semester season
- color migration

Happy 2022! 🥳🍾

### CODE REVIEW

**Review by willespencer — APPROVED** [review]
Thanks for the release and all the work over break Ben! 😄 Tested thoroughly and everything works as expected! Specifically...
- New user walkthrough works
- Mobile view + navbar work
- New year dropdown works
- New majors works
- Minor req fulfillment works from add modal and from drag/drop
- Analytics route displays data for CP team members (and Firebase is still updating)
- AP Exams still fulfill reqs as expected and show up in req debugger

Things to investigate (that do not block approval)
- My colors do not seem to be migrated as I do not have checkmarks on old courses. Is this just true on dev?
image

- Is there a reason some of the starter semesters are minimized? Do we want this behavior?
image

**Review by jessfeng — APPROVED** [review]
Thanks for working so hard on this over winter break, Ben and the team! 🏂 Tested and changes mentioned in the description seem to work as expected! I was going to comment on faulty AP English requirements but it seems like you have that covered already with the draft PR 😄 

Some specific bugs (also added these onto the SP22 Roadmap) 🐛 
- AP Stats is currently counting for Lib Studies in Engineering, but CoE doesn't accept AP Stats as counting for anything
- AP Bio (4 or 5) isn't counting for Lib Studies at the moment, but it should
- Currently allowing `entrance year` >= `graduation year` (maybe put in verification for this)

Things to chew on 🦴 
- Currently, we allow people to add new semesters that are prior to their entrance year (ie. adding Fall 2016 when entrance year is 2020). Is this intentional?
- Might be useful to point out where to provide feedback in the user onboarding/walkthrough (I couldn't find it even though it said it's located on the right side D:) 
- If I added a course already (and it fulfills a requirement) I am able to add the course again to the same semester, but it displays a warning sign indicating a duplicate. Could we just not do anything in this case (ie. don't add the new course, just keep the current state)? If this course satisfies multiple requirements that cannot double count, we can display a pop-up that allows the user to choose which requirement they want the course to count for. 
- Do we make a distinction for Lib Studies before and after FA19? (apparently College of Engineering [does](https://apps.engineering.cornell.edu/liberalstudies/index.cfm) :( )

Fantastic work 💯 and happy lunar new year!! 🏮

**Comment by einc** [comment]
> Thanks for the release and all the work over break Ben! 😄 Tested thoroughly and everything works as expected! Specifically...
> 
> * New user walkthrough works
> * Mobile view + navbar work
> * New year dropdown works
> * New majors works
> * Minor req fulfillment works from add modal and from drag/drop
> * Analytics route displays data for CP team members (and Firebase is still updating)
> * AP Exams still fulfill reqs as expected and show up in req debugger
> 
> Things to investigate (that do not block approval)
> 
> * My colors do not seem to be migrated as I do not have checkmarks on old courses. Is this just true on dev?
>   image
> * Is there a reason some of the starter semesters are minimized? Do we want this behavior?
>   image

My colors seem to be migrated on dev/prod!

**Comment by einc** [comment]
> Thanks for working so hard on this over winter break, Ben and the team! 🏂 Tested and changes mentioned in the description seem to work as expected! I was going to comment on faulty AP English requirements but it seems like you have that covered already with the draft PR 😄
> 
> Some specific bugs (also added these onto the SP22 Roadmap) 🐛
> 
> * AP Stats is currently counting for Lib Studies in Engineering, but CoE doesn't accept AP Stats as counting for anything
> * AP Bio (4 or 5) isn't counting for Lib Studies at the moment, but it should
> * Currently allowing `entrance year` >= `graduation year` (maybe put in verification for this)
> 
> Things to chew on 🦴
> 
> * Currently, we allow people to add new semesters that are prior to their entrance year (ie. adding Fall 2016 when entrance year is 2020). Is this intentional?
> * Might be useful to point out where to provide feedback in the user onboarding/walkthrough (I couldn't find it even though it said it's located on the right side D:)
> * If I added a course already (and it fulfills a requirement) I am able to add the course again to the same semester, but it displays a warning sign indicating a duplicate. Could we just not do anything in this case (ie. don't add the new course, just keep the current state)? If this course satisfies multiple requirements that cannot double count, we can display a pop-up that allows the user to choose which requirement they want the course to count for.
> * Do we make a distinction for Lib Studies before and after FA19? (apparently College of Engineering [does](https://apps.engineering.cornell.edu/liberalstudies/index.cfm) :( )
> 
> Fantastic work 💯 and happy lunar new year!! 🏮

Just to help answer some questions

- This is intentional (for now). We just have a hardcoded range of sems. We added a new feature that auto-generates the semesters based on entrance/end year for new users so I don't see many users adding new semesters unless they delete old sems! 
- Hotjar is only shown if you don't have ad blocker LOL I've also noticed that while you can see it on dev web-app, it doesn't show up on PR deploys for some reason.. But design is working a better way for users to provide feedback this sem!!
- @benjamin-shen @willespencer what do u think about this? i think current behavior is fine as it doesn't seem harmful / less work for us haha but down to change!
- No, but will add to Notion now :)

**Comment by einc** [comment]
This looks amazing Ben 🚀
I helped address some comments above (most are minor and I'm adding to Notion to address later). Could you take a look at Will's color comment tho? My colors seem to be migrated in dev and in this deployed PR, but I've also added/deleted them a lot so maybe I changed it after the migration?

Tested new year dropdown, new majors (& specialization for CS math is solid), analytics route works, and dashboard looks good! Looks good 2 go!

**Comment by willespencer** [comment]
> > * Currently allowing `entrance year` >= `graduation year` (maybe put in verification for this)

Definitely think we should address this as we start to rely on these fields more than we used to!


> > * If I added a course already (and it fulfills a requirement) I am able to add the course again to the same semester, but it displays a warning sign indicating a duplicate. Could we just not do anything in this case (ie. don't add the new course, just keep the current state)? If this course satisfies multiple requirements that cannot double count, we can display a pop-up that allows the user to choose which requirement they want the course to count for.
> * @benjamin-shen @willespencer what do u think about this? i think current behavior is fine as it doesn't seem harmful / less work for us haha but down to change!

I think we should leave this as is? We initially disallowed duplicates but ran into problems of people taking a course many times in different semesters (i.e. INFO 4998), so similarly worried we might not know some case where people can take multiples of the same course in one semester. Also complications with drag and drop - what if someone dragged INFO 4998 into a semester where there already was one - would the course delete itself? Seems easier and harmless to leave it

**Comment by benjamin-shen** [comment]
Agree with all the discussion! Thanks for the thorough reviews <3

> My colors do not seem to be migrated as I do not have checkmarks on old courses. Is this just true on dev?

The colors script will need to be run on prod.

> Is there a reason some of the starter semesters are minimized? Do we want this behavior?

I could not reproduce this. It seems like it was implemented using localStorage rather than firestore in #536 (maybe we should change this). So I suspect this issue is due to persistent data in your browser.

> AP Stats is currently counting for Lib Studies in Engineering, but CoE doesn't accept AP Stats as counting for anything

This is unexpected, there may have been a mistake in the new AP/IB infra implementation. I'll look into this.

> AP Bio (4 or 5) isn't counting for Lib Studies at the moment, but it should

Our data says AP Bio doesn't have any equivalent courses, so this is expected. This can be an easy fix though (maybe after release, since the behavior is the same).

**Pull request merged**
