### PR TITLE
Load Image Asynchronously

### PR DESCRIPTION
**Pull request by zachary0kent**
Loads the images for PDF generation asynchronously

### CODE REVIEW

**Comment by zachary0kent** [comment]
> can you keep this as a draft?

Yeah I'm trying to get the deploy action to run, idk why it isn't

**Comment by noschiff** [comment]
Pretty sure @benjamin-shen changed the actions so that the checks run on the code after it's merged into the branch. Since you have a merge conflict right now, I don't think it can run.

**Comment by zachary0kent** [comment]
@noschiff @vaishnavi17 I think this fixes the download issue

**Review by noschiff — APPROVED** [review]
It works! Async / await for the win!

**Pull request merged**
