### PR TITLE
Change bottombar to fit the new mobile responsive design

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

This PR implements the new design for the bottombar with the new responsive design. There are two main UI change in the new mobile design:

1. bottom bar now can span almost full screen on mobile when expanded
2. Course information now appears before course review and detail.

To make the css more management, I also made some refactoring that moves all the responsive height and width into `BottomBar.vue`, so it becomes much easier to see different width and heights config in one place.

### Test Plan 

Screen Shot 2021-03-08 at 17 18 51
Screen Shot 2021-03-08 at 17 18 54
Screen Shot 2021-03-08 at 17 19 27
Screen Shot 2021-03-08 at 17 19 31

When the screen is small, should we only have one tab that's not in see more:

Screen Shot 2021-03-08 at 17 19 13
Screen Shot 2021-03-08 at 17 19 19

Reference design:
Screen Shot 2021-03-08 at 17 21 16

In the design the font size of the tab is 14px while the rest is 16px, that's how the design can fit in two tabs. However, I'm not sure whether we should reduce the font size of the tab just to fit in more tabs. Loop in @yuxuanchenn.

### CODE REVIEW

**Comment by hanywang2** [comment]
Hey gang! I miss you all 🥺. Here's an issue I found on the text in the tabs from the updated bottom bar
Screen Shot 2021-03-09 at 1 33 22 AM

Screen Shot 2021-03-09 at 1 34 45 AM

**Comment by SamChou19815** [comment]
@hanywang2 issue fixed

**Review by tcho6319 — CHANGES_REQUESTED** [review]
Thanks Sam! 
I found some issues with how the bottom bar looks on the smaller breakpoints: 

https://user-images.githubusercontent.com/54298311/110836786-75d77500-826e-11eb-910b-d135125487ba.mov

I wonder if it's because we're not accounting for some of the other breakpoints in `BottomBar.vue`.
https://github.com/cornell-dti/course-plan/blob/2942097455f7d6d2b97a52c32d590d5b83065d5c/src/assets/scss/_variables.scss#L37-L40

**Comment by SamChou19815** [comment]
@tcho6319 issue fixed. turns out it's due to a missing `left: 0`

**Review by tcho6319 — APPROVED** [review]
LGTM! 🥳  Thanks Sam. 

> In the design the font size of the tab is 14px while the rest is 16px, that's how the design can fit in two tabs. However, I'm not sure whether we should reduce the font size of the tab just to fit in more tabs. 

You bring up good points that hopefully @yuxuanchenn can address. I'm good with this PR being merged in as is and resolving that design question in another PR, but I understand if you'd want to wait a bit to get Yuxuan's opinion. I'll bump your PR to her in cp-pr channel.

**Pull request merged**
