### PR TITLE
Fall 2023 Pre-enroll Release

### PR DESCRIPTION
**Pull request by zachary-kent**
### Summary 

Imports Spring 2024 courses for Fall 2023 pre-enroll. There are few major changes beyond this, so hopefully reviewing this will be pretty simple. 

### Test Plan 

There aren't any user-facing changes besides the addition of new courses, so just go through the motions of testing a generic frontend change.

### CODE REVIEW

**Review by nidhi-mylavarapu — APPROVED** [review]
Just read over all the file changes + ran everything and it looks good!😁

**Review by nidhi-mylavarapu — APPROVED** [review]
Just read over all the file changes + ran everything and it looks good!😁

**Review by andxu282 — APPROVED** [review]
3-4

**Review by KaylinChan — APPROVED** [review]
I tested adding some new courses and reviewed the file changes, looks good!

**Pull request merged**
