### PR TITLE
Fall 2022 Pre-Enroll Release

### PR DESCRIPTION
**Pull request by noschiff**
# Summary 

This pull request introduces the Tools page, featuring personalized advisor information, a progress tracker, a PDF schedule export option, and a collection of useful links! It also updates the course data in preparation for Spring 2023 pre-enroll and improves the development workflow.

### Tools Page
- [x] Tools Page, Advisors Card, and Advisors Backend #690 (@noschiff)
- [x] Improve Tool Cards and Tools Page #719 (@noschiff @zachary0kent)
- [x] Tools Page Formatting & Useful Links #726 (@noschiff)
- [x] Touch Up Useful Links Tool Card #740 (@noschiff @benjamin-shen)
- [x] Add Advisors Data (#734 (@noschiff @zachary0kent)
- [x] Create Export Schedule Tool Card #748 (@noschiff)
- [x] Relocate Requirement Progress Calculation #750 (@noschiff)
- [x] Create Progress Tracker Tool Card #751 (@noschiff @zachary0kent @andxu282)
- [x] Function to generate user's course PDF #730 (@vaishnavi17 @zachary0kent @benjamin-shen @noschiff)
- [x] Remove tools feature flag #746 (@zachary0kent)
- [x] Fix Navigation Bug #757 (@zachary0kent)
- [x] Small PDF generation bug fixes #758 (@vaishnavi17)
- [x] Quick Touch Up to Tools Page #760 (@noschiff)

### Workflow and Utility
- [x] Fix failing requirements sidebar Cypress test #697 (@willespencer)
- [x] Copy Data Between Users Across Dev & Prod #711 (@noschiff)
- [x] Fix Script Copy Data Between Users #715 (@noschiff)
- [x] refactor global firestore data files #717 (@benjamin-shen)
- [x] update contributors #718 (@noschiff)
- [x] remove firebase functions #721 (@benjamin-shen)
- [x] Clean Data in Course Generator Script #720 (@noschiff)
- [x] Update Courses for Winter and Spring 2023 #727 (@noschiff)
- [x] Fix requirements json after #727 #729 (@benjamin-shen)
- [x] Update scripts #724 (@benjamin-shen)
- [x] Move docs to wiki #731 (@benjamin-shen)
- [x] Clean up workflows, add update-courses workflow #728 (@benjamin-shen)
- [x] Write script outputs to ignored directory #735 (@benjamin-shen)
- [x] Update Copy User Data Script Documentation (#739 (@noschiff)
- [x] Update update-courses workflow #736 (@benjamin-shen)
- [x] Remove semester type from database #595 (@benjamin-shen)
- [x] Fix linting for enums #752 (@zachary0kent)
- [x] Update courseplan email #755 (@benjamin-shen)
- [x] Update Courses (FA22-Nov1) #756 (@benjamin-shen @noschiff)
- [x] Reorganize tools in codebase #759 (@benjamin-shen)

### Requirements
- [x] Implement Alternate Options for Engineering Physics Major #687 (@noschiff)
- [x] Add psych major #709 (@benjamin-shen @kkkehui)
- [x] rename human policy to health policy #733 (@benjamin-shen)

### Gatekept Features

- [x] Two-graph requirement header progress colors and warnings #622 (@willespencer @SamChou19815)
- [x] Populate conflict modal with requirements #669 (@willespencer @SamChou19815)
- [x] Setup backend infra for CASE exams #641 (@benjamin-shen @willespencer)
- [x] Add transfer credits and save confirmation modal (#691)  (@jerrry1123 @willespencer)
- [x] Added new profile container with the first page of settings #675 (@jerrry1123)
- [x] capitalize 'get' in profile container #732 (@benjamin-shen)
- [x] Profile Page Feature Flag #743 (@zachary0kent)

# Test Plan 

Confirm everything works as expected on all pages of CoursePlan site, especially on the Tools page and navigating between pages, with no console errors. 

For example:
- Navigate between the plans page, tools page, and profile pop-up and ensure you get where you expect to be!
- Collapse and expand the Tool Cards and resize the screen for the Tools Page. You can refresh to ensure the collapsed state persists!
- Add some majors and minors and look at the advisors!
- Put some courses into your schedule and download the PDF!
- Ensure progress tracker displays information for all colleges/majors/minors/grad programs and the bar represents the correct progress.
- Visit the useful links!
- Check that a new course such as AEP 3100 can be added and that the bottom bar shows up with expected information for it.

preview

# Notes 
Do not squash and merge.

### CODE REVIEW

**Comment by noschiff** [comment]
**GET HYPED! IT'S FINALLY TIME TO REVIEW!** @zachary0kent @benjamin-shen @andxu282

**Comment by benjamin-shen** [comment]
Yay!!! A long-awaited release :)) Major props to everyone who worked on this! 🥳 

I sometimes am blocked from scrolling on the Tools page when it's horizontally shrunk, but idk whether or not the issue is specific to my machine/browser. If anyone else runs into this, lmk!

PDF generation looks and works great! I did find some issues:
- If there are any long major names, it's possible for the text to overflow. Here is an example of an info sci & chem/biomolecular engineering double major. image
- Downloading the PDF fails if there are any requirements that cannot be looked up (say, if the user switched/removed their college/major/minor/grad affiliation). The error message is `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')`. To reproduce: add CS major, add selectable req (eg. CS 4700 as Technical Elective), remove CS major, and try to download the pdf. A fix would be to omit the requirement from the pdf tables if it's not found in the `userRequirementsMap`.
- The gap does look a little funny for AP credit, could we add an emoji? Also, could we capitalize "Credit"? image
- If someone is crazy enough to take 100 courses in a single semester (and the table does overflow), this rounded table edge artifact shows up on the second page. Not a huge issue but just something interesting to notice. image

All the useful links work! Advisors are properly changing when I switch my college/major! The progress tracker seems to be working as intended!

How I feel rn:
image

**Comment by andxu282** [comment]
Everything looks really good! I added multiple majors and minors, and it seems like the advisors and useful links toolcards work as intended. I saw the same text overflow issue in the pdf as Ben did:
Capture d’écran 2022-11-03 à 12 46 14 PM

One thing that I think is unrelated to these changes (hopefully) is that when I have zero classes, it still says I fulfilled 1/7 requirements here (to replicate: add Biological Sciences, Astronomy, Earth and Atmospheric Sciences as majors and no classes)
Capture d’écran 2022-11-03 à 12 39 06 PM

The progress bar matches along with the fractions next to it for the most part, but I will look into fixing this issue mentioned here:
image

**Comment by noschiff** [comment]
> One thing that I think is unrelated to these changes (hopefully) is that when I have zero classes, it still says I fulfilled 1/7 requirements here (to replicate: add Biological Sciences, Astronomy, Earth and Atmospheric Sciences as majors and no classes) Capture d’écran 2022-11-03 à 12 39 06 PM

@andxu282 I think that this might have something to do with APs. I'm pretty sure we exclude purely self check requirements from the progress bar (like for the Applied Math Minor, we say 1/1 when you've finished Math 2930 & 2940 and completely ignore the core required courses because they're self check). I remember being confused by this as well back when I reviewed Jerry's PR. Maybe take a look at the requirement debugger and see if you can figure out where the 1 is coming from? Either way, it probably wouldn't come from this release, but we should definitely try to clean it up. It would be really great if you could figure this out because I've definitely had the same weird behavior before. If you don't have any transfer credit… then maybe the 1/1 is from the swim test? I doubt it because it should show up in the completed section. It's super weird when we get a completed requirement that doesn't show up as completed anywhere…
image

**Comment by noschiff** [comment]
> Everything looks really good! I added multiple majors and minors, and it seems like the advisors and useful links toolcards work as intended. I saw the same text overflow issue in the pdf as Ben did:

@andxu282 This should hopefully be fixed in #758 :)

**Comment by zachary0kent** [comment]
Screen Shot 2022-11-03 at 8 30 01 PM
I don't think this is something to block on, but some advisors who correspond to multiple majors are duplicated. We should probably either show each advisor once or (probably better) display which major each advisor corresponds to.

**Comment by zachary0kent** [comment]
Screen Shot 2022-11-03 at 8 36 53 PM
PDF generation handles every major in engineering!

**Review by vaishnavi17 — APPROVED** [review]
Thanks everyone for working on this (and helping out so much with PDF gen!). I checked out PDF gen and the other toolcards like progress on the preview link, and it all looks good to me!

For future work, it would be cool to display the particular major and college for each of the advisors, and have the "plan" or "tools" button highlighted when we are viewing that page. I can definitely help out with those features.

**Review by zachary0kent — APPROVED** [review]
Looks good to me! Thank you everyone for all of the hard work! Tested the following features:

- PDF generation (with a copious number of majors)
- Squeezing and stretching the progress tracker (everything wraps great!)
- The progress tracker does indeed track progress (with motivational emojis to boot!)
- Invaluable links

**Review by benjamin-shen — APPROVED** [review]

**Pull request merged**
