### PR TITLE
convertSemesters in Dashboard.vue -> firestoreSemestersToAppSemesters

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

Depending on #184!

Since convertSemesters is now a complete pure function, let's move it into user-data.ts for consistency.

### Test Plan 

👀

### CODE REVIEW

**Comment by hanywang2** [comment]
Why does this branch not require a review?

**Comment by SamChou19815** [comment]
> Why does this branch not require a review?

The target branch is not master. I usually use this setup to emulate stacked diffs at FB

**Comment by hanywang2** [comment]
O I am tripping that is right

**Review by hanywang2 — APPROVED** [review]
This is an easy review since it's just renaming and moving the location of the function. Please stop me if there's anything I'm missing

**Pull request merged**
