### PR TITLE
Created a reset modal for subreq

### PR DESCRIPTION
**Pull request by neketka**
### Summary

This pull request creates a confirmation modal when a user attempts to reset a sub-requirement.

- [x] Implemented modal for confirmation of main/transfer credits
- [x] Added modal to reset action

Remaining TODOs:

- [ ] I could not for the life of me figure out how to avoid the "transform" in the style after traveling up and down component trees from the other modals
- [ ] Need the ability to have a unique id for transfer credit or else deleting them will require many changes across 5 functions that may have deeply nested event handlers (possible merge conflicts)
- [ ] Possible media query for mobile devices to change the size of the modal for mobile devices

Desktop:
image

Phone:
image

### Test Plan 

Keep testing if the reset functionality works on everything (maybe except transfer credits for now)

### Notes

The v-model modal functionality might be useful in the future.

### CODE REVIEW

**Comment by neketka** [comment]
Fixed the above and resolved merge conflict.

**Review by SamChou19815 — APPROVED** [review]
LGTM

**Comment by SamChou19815** [comment]
> Need the ability to have a unique id for transfer credit or else deleting them will require many changes across 5 functions that may have deeply nested event handlers (possible merge conflicts)

We can potentially pair-programming where I can pass down more information from requirement algo to help unblock this.

**Review by tcho6319 — COMMENTED** [review]
Thanks @neketka! So excited to see our Reset modal 🥰
I know this PR is already merged in but I left some comments to document additional TODOs for finishing up this feature in future PR(s) in Sprint 3.8. 

1. There seem to be smaller discrepancies with the design (i.e. the text color in the modal, the border color of the "No" button). 
Screen Shot 2021-03-11 at 12 54 38 PM
Screen Shot 2021-03-11 at 12 55 09 PM

**Pull request merged**
