### PR TITLE
Implement a simple CLI to dump requirement graph of a user

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

This PR implements a CLI that allows you to dump the requirement graph to the console. The tool itself isn't particularly useful since we already have a requirement debugger in the frontend. Its main purpose is to produce a starting point to do those requirement-graph-aware data migrations, since this tool shows how to query and build the requirement graph from the data using `firebase-admin`.

The implementation itself is very straightforward, since all the functions are already there. However, I do need to do some refactor to break the cyclic import between `store`, `global-firestore-data` and `user-data-converter`. The final dependency structure becomes

```

global-firestore-data
    |        |
    |       store
    |        |
user-data-converter 

```

### Test Plan 

<details>
<summary>Running `npm run req-graph-dump [your email]` produces something like:</summary>

```txt
User Requirements:
  College-UNI-Physical Education
  College-EN-Mathematics
  College-EN-Physics
  College-EN-Chemistry
  College-EN-First-Year Writing Seminars
  College-EN-Computing
  College-EN-Introduction to Engineering
  College-EN-Engineering Distribution
  College-EN-Liberal Studies: 6 courses
  College-EN-Advisor-Approved Electives
  College-EN-Engineering Communications
  Major-CS-Introductory Programming
  Major-CS-Computer Science Core
  Major-CS-CS Electives
  Major-CS-CS Practicum or Project
  Major-CS-Technical Electives
  Major-CS-External Specialization
  Major-CS-Major-approved Elective(s)
  Major-CS-Probability
  Minor-MATH-Math Minor Prerequisites
  Minor-MATH-Four 3000 or 4000 level MATH courses
User courses:
  { uniqueId: 84, courseId: 352308, code: 'MATH 3110' }
  { uniqueId: 42, courseId: 352255, code: 'MATH 1910' }
  { uniqueId: 43, courseId: 352257, code: 'MATH 1920' }
  { uniqueId: 44, courseId: 352295, code: 'MATH 2930' }
  { uniqueId: 71, courseId: 352307, code: 'MATH 2940' }
  { uniqueId: 89, courseId: 351444, code: 'COGST 1101' }
  { uniqueId: 90, courseId: 354639, code: 'SOC 1101' }
  { uniqueId: 91, courseId: 352728, code: 'LING 1101' }
  { uniqueId: 92, courseId: 359378, code: 'ECON 2040' }
  { uniqueId: 93, courseId: 350281, code: 'ASIAN 2212' }
  { uniqueId: 69, courseId: 364536, code: 'CS 2112' }
  { uniqueId: 37, courseId: 358552, code: 'CS 2800' }
  { uniqueId: 38, courseId: 358556, code: 'CS 3110' }
  { uniqueId: 39, courseId: 358560, code: 'CS 3410' }
  { uniqueId: 40, courseId: 358595, code: 'CS 4820' }
  { uniqueId: 41, courseId: 358572, code: 'CS 4410' }
  { uniqueId: 54, courseId: 358569, code: 'CS 4110' }
  { uniqueId: 66, courseId: 358570, code: 'CS 4120' }
  { uniqueId: 58, courseId: 358571, code: 'CS 4121' }
  { uniqueId: 67, courseId: 358592, code: 'CS 4780' }
  { uniqueId: 68, courseId: 365294, code: 'CS 5114' }
  { uniqueId: 52, courseId: 350378, code: 'PE 1330' }
  { uniqueId: 53, courseId: 361736, code: 'PE 1657' }
  { uniqueId: 50, courseId: 369210, code: 'INFO 4998' }
  { uniqueId: 51, courseId: 369210, code: 'INFO 4998' }
  { uniqueId: 47, courseId: 368276, code: 'HIST 1200' }
  { uniqueId: 48, courseId: 368276, code: 'HIST 1200' }
  { uniqueId: 49, courseId: 354919, code: 'ENGRI 1220' }
  { uniqueId: -2, courseId: 358526, code: 'AP Computer Science A' }
  {
    uniqueId: -3,
    courseId: 355207,
    code: 'AP Physics C-Electricity & Magnetism'
  }
  { uniqueId: -4, courseId: 355146, code: 'AP Physics C-Mechanics' }
  { uniqueId: -5, courseId: 359187, code: 'IB Chemistry' }
Edges:
  College-UNI-Physical Education -> { uniqueId: 52, courseId: 350378, code: 'PE 1330' }
  College-UNI-Physical Education -> { uniqueId: 53, courseId: 361736, code: 'PE 1657' }
  College-EN-Mathematics -> { uniqueId: 42, courseId: 352255, code: 'MATH 1910' }
  College-EN-Mathematics -> { uniqueId: 43, courseId: 352257, code: 'MATH 1920' }
  College-EN-Mathematics -> { uniqueId: 44, courseId: 352295, code: 'MATH 2930' }
  College-EN-Physics -> { uniqueId: -4, courseId: 355146, code: 'AP Physics C-Mechanics' }
  College-EN-Physics -> {
    uniqueId: -3,
    courseId: 355207,
    code: 'AP Physics C-Electricity & Magnetism'
  }
  College-EN-Chemistry -> { uniqueId: -5, courseId: 359187, code: 'IB Chemistry' }
  College-EN-First-Year Writing Seminars -> { uniqueId: 47, courseId: 368276, code: 'HIST 1200' }
  College-EN-First-Year Writing Seminars -> { uniqueId: 48, courseId: 368276, code: 'HIST 1200' }
  College-EN-Computing -> { uniqueId: -2, courseId: 358526, code: 'AP Computer Science A' }
  College-EN-Introduction to Engineering -> { uniqueId: 49, courseId: 354919, code: 'ENGRI 1220' }
  College-EN-Engineering Distribution -> { uniqueId: 69, courseId: 364536, code: 'CS 2112' }
  College-EN-Liberal Studies: 6 courses -> { uniqueId: 93, courseId: 350281, code: 'ASIAN 2212' }
  College-EN-Liberal Studies: 6 courses -> { uniqueId: 89, courseId: 351444, code: 'COGST 1101' }
  College-EN-Liberal Studies: 6 courses -> { uniqueId: 91, courseId: 352728, code: 'LING 1101' }
  College-EN-Liberal Studies: 6 courses -> { uniqueId: 90, courseId: 354639, code: 'SOC 1101' }
  College-EN-Liberal Studies: 6 courses -> { uniqueId: 92, courseId: 359378, code: 'ECON 2040' }
  College-EN-Advisor-Approved Electives -> { uniqueId: -4, courseId: 355146, code: 'AP Physics C-Mechanics' }
  College-EN-Advisor-Approved Electives -> {
    uniqueId: -3,
    courseId: 355207,
    code: 'AP Physics C-Electricity & Magnetism'
  }
  College-EN-Advisor-Approved Electives -> { uniqueId: -2, courseId: 358526, code: 'AP Computer Science A' }
  College-EN-Advisor-Approved Electives -> { uniqueId: -5, courseId: 359187, code: 'IB Chemistry' }
  Major-CS-Introductory Programming -> { uniqueId: -2, courseId: 358526, code: 'AP Computer Science A' }
  Major-CS-Introductory Programming -> { uniqueId: 69, courseId: 364536, code: 'CS 2112' }
  Major-CS-Computer Science Core -> { uniqueId: 37, courseId: 358552, code: 'CS 2800' }
  Major-CS-Computer Science Core -> { uniqueId: 38, courseId: 358556, code: 'CS 3110' }
  Major-CS-Computer Science Core -> { uniqueId: 39, courseId: 358560, code: 'CS 3410' }
  Major-CS-Computer Science Core -> { uniqueId: 40, courseId: 358595, code: 'CS 4820' }
  Major-CS-Computer Science Core -> { uniqueId: 41, courseId: 358572, code: 'CS 4410' }
  Major-CS-CS Electives -> { uniqueId: 54, courseId: 358569, code: 'CS 4110' }
  Major-CS-CS Electives -> { uniqueId: 68, courseId: 365294, code: 'CS 5114' }
  Major-CS-CS Practicum or Project -> { uniqueId: 58, courseId: 358571, code: 'CS 4121' }
  Major-CS-Technical Electives -> { uniqueId: 66, courseId: 358570, code: 'CS 4120' }
  Major-CS-Technical Electives -> { uniqueId: 67, courseId: 358592, code: 'CS 4780' }
  Major-CS-Major-approved Elective(s) -> { uniqueId: -4, courseId: 355146, code: 'AP Physics C-Mechanics' }
  Major-CS-Major-approved Elective(s) -> {
    uniqueId: -3,
    courseId: 355207,
    code: 'AP Physics C-Electricity & Magnetism'
  }
  Major-CS-Major-approved Elective(s) -> { uniqueId: -2, courseId: 358526, code: 'AP Computer Science A' }
  Major-CS-Major-approved Elective(s) -> { uniqueId: -5, courseId: 359187, code: 'IB Chemistry' }
  Minor-MATH-Math Minor Prerequisites -> { uniqueId: 71, courseId: 352307, code: 'MATH 2940' }
  Minor-MATH-Math Minor Prerequisites -> { uniqueId: 43, courseId: 352257, code: 'MATH 1920' }
  Minor-MATH-Four 3000 or 4000 level MATH courses -> { uniqueId: 84, courseId: 352308, code: 'MATH 3110' }

```

</details>

### Notes

Future applications:

- graph-aware data migration script
- typed firestore access for other firebase backend functions
- integration tests of requirement computation on real data.

### CODE REVIEW

**Comment by hahnbeelee** [comment]
I'm getting this error when I run `npm run req-graph-dump`
image

**Comment by SamChou19815** [comment]
> I'm getting this error when I run `npm run req-graph-dump`
> 
> image
> 
> 

@hahnbeelee 
The serviceAccount.json file is needed for cypress testing as well. You can find it on notion.

**Comment by hahnbeelee** [comment]
I'm getting this now. :/
image

**Comment by SamChou19815** [comment]
@hahnbeelee The command should be `npm run req-graph-dump [your email]`. I updated the description.

**Review by hahnbeelee — APPROVED** [review]
LGTM! Cool stuff.
image

**Pull request merged**
