### PR TITLE
Add self to contributors

### PR DESCRIPTION
**Pull request by Destaq**
### Summary 

Made a contribution (see #869) and so get to be on the contributors list 🎉

### CODE REVIEW

**Review by andxu282 — APPROVED** [review]
let's goooo

**Comment by nidhi-mylavarapu** [comment]
Looks good!! Welcome to the team :)

**Review by nidhi-mylavarapu — APPROVED** [review]
Looks good!! Welcome to the team :)

**Comment by Destaq** [comment]
Great thanks! I guess I'm good to go on merging this?

**Pull request merged**
