### PR TITLE
Spring 2022 Pre-enroll Release

### PR DESCRIPTION
**Pull request by willespencer**
### Summary 

This pull request pushes the course data for next semester (Fall 2022) before Spring 2022 pre-enroll, in addition to new features merged this semester. 🥳 

- [x] #677 (@noschiff)
- [x] #639 (@benjamin-shen)
- [x] #661 #663 #667 (@jerrry1123 @andxu282 @noschiff)
- [x] #655 (@noschiff)
- [x] #647 (@willespencer)
- [x] #664 (@willespencer)
- [x] #668 (@noschiff)
- [x] #618 (@zachary0kent @willespencer)
- [x] #673 (@willespencer)
- [x] #676 (@benjamin-shen)
- [x] #666 (@noschiff) 
- [x] #681 (@noschiff)
- [x] #670 (@jerrry1123) 
- [x] #683 (@willespencer)
- [x] #684 (@willespencer)  
- [x] #686 (@noschiff)
- [x] #665 (@andxu282) 

Other features merged that are gatekept and thus will not show for real users
- [x] #659 (@willespencer)
- [x] #621 (@willespencer)

### Test Plan 

Confirm everything works as expected on all pages of CoursePlan site, especially related to new features, with no console log errors. Examples...
- [x] Add a class with new Fall 2022 course data
- [x] Confirm warning icons show on compact courses.
- [x] Confirm onboarding has entrance grad seasons, and the year dropdowns populate correctly.
- [x] Confirm A&S works as expected, and reqs switch if entrance sem goes before/after Fall 2020.
- [x] Confirm AP/IB code and new conflict code is not accessible unless the feature flag is turned on.

### CODE REVIEW

**Comment by einc** [comment]
Talked offline, but adding here so we don't forget. 

We're switching on the feature flag for AP/IB from PR #676, even if we are running into AP bugs as we don't have the opt in/out feature ready yet so users wouldn't have a workaround for adding AP courses if we temp disabled them. 

For now, we'll also just add a warning msg about transfer credits during onboarding alerting users we are working on it. Designers are also working on a more visible way to notify users of new updates

Screen Shot 2022-04-20 at 1 16 29 PM

**Review by jessfeng — APPROVED** [review]
Thanks for all the hard work semester!! 🚀 Tested and confirmed
- adding class for FA22 semester
- adding class for SU22 semester
- viewing warning icon in compact mode
- entrance/grad semester and year validation
- stars are not seen for info fields in onboarding review page
- honors physics track is present and selectable 
- inequality minor is selectable + requirements look pretty good
- looked over cypress test suite code and it looks fine?

**Review by jerrry1123 — APPROVED** [review]
Testing everything one by one:
- New fall and summer courses appear to be present (i picked a few at random)
- Not 100% sure how to test the AP/IB requirements since I don't know what errors Ben's PR was fixing, but I tested a few AP courses and they seem to satisfy the requirements they're supposed to. At least the basic functionality works, I'm sure that the more complex stuff is really bugged but the warning does appear and is big enough to grab my attention. 
- README looks legit
- Warning appears properly in compact mode 
image
- Seasons are properly required in onboarding and the years are properly ordered
- Random green star properly removed in onboarding confirmation
- Honors physics properly fulfills the physics requirement, and also major specific alternative electives work (e.g. this is what AEP majors see)
image
- AP credits and A&S requirements now work together nicely

**Review by noschiff — APPROVED** [review]
Thanks to everyone for all their contributions; we've made great progress with this release!

I verified that:
- new classes for FA22 (e.g. ILRHR 5645) can be added to the schedule
- classes offered in FA22 (e.g. CS 2112) have up-to-date lecture and instructor information
- compact view preserves warnings
- the transfer credits warning appears
- A&S college and requirements change depending on entrance year
- entrance and graduation year drop-downs are automatically populated & respond correctly to invalid selections
- total academic credits and A&S credits are computed correctly
- there are no stars on the onboarding review page
- AP credits are automatically applied
- inequality minor and fashion design major function
- honors physics courses count for COE physics requirement

We have console warnings when the user adds a course that is not on CUReview's website, but this won't be an issue once CUReviews updates their data.

**Pull request merged**
